---@meta

---@diagnostic disable: duplicate-doc-alias

---@enum PREFAB_ASSET
RESOURCE_TYPE = {
	PREFAB_FOUNTAIN = "PREFAB_FOUNTAIN",
	PREFAB_FOUNTAIN_CONSTRUCTION = "PREFAB_FOUNTAIN_CONSTRUCTION",
}

---@enum ATLAS_CELL_ASSET
RESOURCE_TYPE = {
	ICON_ASTEROID_ROCK = "ICON_ASTEROID_ROCK"
}

---@enum RESOURCE_TYPE
RESOURCE_TYPE = {
	SPACE_LUXURY = "SPACE_LUXURY"
}

---@enum RESOURCE_ASSET
RESOURCE_ASSET = {
    ASTEROID_ROCK = "ASTEROID_ROCK"
}

---@enum BUILDING_PART_TYPE
BUILDING_PART_TYPE = {
    LOCATOR = "LOCATOR",
}